###
POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "id": 100628414436352,
  "memberId": 1624581077500825600,
  "name": "test2",
  "idCard": "123321",
  "type": "1"
}

###
POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "name": "wccc",
  "idCard": "123321",
  "type": "1"
}

###
POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "id": "1694249334754906112",
  "memberId": "1693620129994248192",
  "name": "notwcovo",
  "idCard": "123321",
  "type": "1"
}


###
